#!/usr/bin/env bash
# =====================================================================
# slurm-source.sh - build and install Slurm 25.11 from source at /opt/slurm
#
# WHY SOURCE: the nodes ship a vendor Slurm (23.02 cm10.0) that lacks
# features the SOW needs, and Ubuntu's slurm-wlm is only 21.08. Building
# 25.11 also guarantees --with-nvml, without which GRES silently fails
# and slurmctld DRAINs the node ("gres/gpu count reported lower than
# configured").
#
# Run on BOTH nodes (controller and compute need the identical build).
#   sudo SLURM_MODE=source bash scripts/03-slurm-controller.sh
#
# Verified: configure reports HAVE_NVML 1 with libnvidia-ml-dev present.
# Without that package HAVE_NVML is UNDEFINED and GRES breaks silently.
# =====================================================================
set -euo pipefail

SLURM_VER="${SLURM_VER:-25.11.8}"
PREFIX="${PREFIX:-/opt/slurm}"
SYSCONFDIR="${SYSCONFDIR:-/etc/slurm}"
JOBS="${JOBS:-$(nproc)}"
SRC_DIR="${SRC_DIR:-/usr/local/src}"
TARBALL_URL="https://download.schedmd.com/slurm/slurm-${SLURM_VER}.tar.bz2"

hr() { printf '\n==> %s\n' "$*"; }

hr "Slurm ${SLURM_VER} source build -> ${PREFIX}"

# ---------------------------------------------------------------
# 1. Build dependencies
#    libnvidia-ml-dev is MANDATORY: it provides nvml.h. Without it
#    configure sets HAVE_NVML undefined and GPU GRES will not work.
# ---------------------------------------------------------------
hr "installing build dependencies"
export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_MODE=a
export NEEDRESTART_SUSPEND=1
apt-get update -qq
apt-get install -y -qq \
  build-essential pkg-config m4 bzip2 wget \
  libmunge-dev libmariadb-dev \
  libjson-c-dev libhdf5-dev libhttp-parser-dev libyaml-dev \
  libjwt-dev libdbus-1-dev libssl-dev libpam0g-dev \
  libpmix-dev libnvidia-ml-dev 2>&1 | tail -3

# ---------------------------------------------------------------
# 2. Fetch + extract
# ---------------------------------------------------------------
mkdir -p "$SRC_DIR"
cd "$SRC_DIR"
if [[ ! -d "slurm-${SLURM_VER}" ]]; then
  hr "downloading ${TARBALL_URL}"
  curl -fsSL -o "slurm-${SLURM_VER}.tar.bz2" "$TARBALL_URL"
  tar xjf "slurm-${SLURM_VER}.tar.bz2"
fi
cd "slurm-${SLURM_VER}"

# ---------------------------------------------------------------
# 3. Configure
#    --with-nvml is left to autodetection BUT we verify it afterwards,
#    because silent failure here is the worst outcome.
# ---------------------------------------------------------------
hr "configure (--prefix=${PREFIX} --sysconfdir=${SYSCONFDIR})"
make distclean >/dev/null 2>&1 || true
# Disable ROCm/SMI: the distro round-robin library makes configure detect
# rocm_smi and slurmd then throws "Exception caught: rsmi_init" on nodes
# with no AMD GPU. Harmless but noisy; --without-rsmi keeps logs clean.
./configure --prefix="$PREFIX" --sysconfdir="$SYSCONFDIR" \
  --with-pmix --without-rsmi \
  >/tmp/slurm-configure.log 2>&1 || {
    echo "!! configure failed - last 20 lines:"; tail -20 /tmp/slurm-configure.log; exit 1; }

# ---------------------------------------------------------------
# 4a. cgroup config - 25.11 warns cgroup/v1 is deprecated, but forcing
#     v2 on a host that only has hybrid cgroups makes slurmd die with
#     "fatal: /sys/fs/cgroup is not a valid cgroup2 mountpoint".
#     Gate it on actual detection so the script works on both.
# ---------------------------------------------------------------
CG_TYPE="$(stat -fc %T /sys/fs/cgroup 2>/dev/null || echo unknown)"
if [[ "$CG_TYPE" == "cgroup2fs" ]]; then
  CG_PLUGIN="cgroup/v2"
  echo "    cgroup v2 detected -> CgroupPlugin=cgroup/v2"
else
  CG_PLUGIN="cgroup/v1"
  echo "    !! /sys/fs/cgroup is '${CG_TYPE}' (not cgroup2fs) -> falling back to cgroup/v1"
  echo "       On the i3D H200 nodes this should read cgroup2fs; verify with:"
  echo "         stat -fc %T /sys/fs/cgroup"
fi
mkdir -p /etc/slurm
cat > /etc/slurm/cgroup.conf <<EOF
# Slurm cgroup config (auto-generated by 03-slurm-controller.sh)
CgroupPlugin=${CG_PLUGIN}
ConstrainCores=yes
ConstrainDevices=yes
ConstrainRAMSpace=yes
EOF
echo "    wrote /etc/slurm/cgroup.conf (${CG_PLUGIN})"

# ---------------------------------------------------------------
# 4. VERIFY NVML - the whole reason for building from source
# ---------------------------------------------------------------
hr "verifying NVML support"
if grep -q '^#define HAVE_NVML 1' config.h; then
  echo "    HAVE_NVML 1  -> GPU GRES will work"
else
  echo
  echo "    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  echo "    !! HAVE_NVML is NOT defined - GPU GRES WILL NOT WORK."
  echo "    !! nvml.h was not found. Install it and re-run:"
  echo "    !!     apt-get install -y libnvidia-ml-dev"
  echo "    !!     ls /usr/include/nvml.h"
  echo "    !! Refusing to install a build without NVML, because"
  echo "    !! slurmctld would DRAIN the GPU nodes at registration."
  echo "    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  exit 1
fi
grep -iE "checking for nvml|checking for pmix" /tmp/slurm-configure.log | head -4 | sed 's/^/    /'

# ---------------------------------------------------------------
# 5. Build + install
# ---------------------------------------------------------------
hr "building with ${JOBS} jobs (this takes a while)"
START=$(date +%s)
make -j"$JOBS" >/tmp/slurm-build.log 2>&1 || {
  echo "!! build failed - last 25 lines:"; tail -25 /tmp/slurm-build.log; exit 1; }
make install >/tmp/slurm-install.log 2>&1 || {
  echo "!! install failed - last 20 lines:"; tail -20 /tmp/slurm-install.log; exit 1; }
echo "    build+install took $(( $(date +%s) - START ))s"

# ---------------------------------------------------------------
# 6. PATH + linker so every tool finds this build
# ---------------------------------------------------------------
hr "wiring PATH and ld.so"
cat > /etc/profile.d/slurm.sh <<EOF
# Slurm built from source (scripts/slurm-source.sh)
export PATH=${PREFIX}/bin:${PREFIX}/sbin:\$PATH
export MANPATH=${PREFIX}/share/man:\$MANPATH
EOF
chmod 644 /etc/profile.d/slurm.sh
echo "${PREFIX}/lib" > /etc/ld.so.conf.d/slurm.conf
ldconfig

# Pyxis (and any SPANK plugin) compiles against spank.h. A source install
# puts headers under ${PREFIX}/include, which is NOT on the default
# compiler path - so symlink them, otherwise pyxis fails to build.
mkdir -p /usr/include/slurm
ln -sf "${PREFIX}"/include/slurm/*.h /usr/include/slurm/ 2>/dev/null || true
echo "    linked headers into /usr/include/slurm (for Pyxis)"

# ---------------------------------------------------------------
# 6b. systemd units - a source install provides none, and 03/04 start
#     these services by name, so create them pointing at ${PREFIX}.
# ---------------------------------------------------------------
hr "installing systemd units"
install_unit() {   # $1=name  $2=exec  $3=description
  # Type=simple with -D (foreground): Slurm daemons fork by default, and
  # Type=forking + PIDFile races the pid-file creation, producing
  # "Can't open PID file ... (yet?)" and eventually a start timeout.
  # Running in the foreground removes that race entirely.
  cat > "/etc/systemd/system/$1.service" <<EOF
[Unit]
Description=$3
After=network.target munge.service
Wants=munge.service

[Service]
Type=simple
ExecStart=$2 -D
ExecReload=/bin/kill -HUP \$MAINPID
User=root
Restart=on-failure
RestartSec=5
TimeoutStartSec=120

[Install]
WantedBy=multi-user.target
EOF
  echo "    $1.service -> $2 -D (foreground)"
}
install_unit slurmctld "${PREFIX}/sbin/slurmctld" "Slurm controller daemon"
install_unit slurmd    "${PREFIX}/sbin/slurmd"    "Slurm node daemon"
install_unit slurmdbd  "${PREFIX}/sbin/slurmdbd"  "Slurm DBD accounting daemon"
# slurmdbd needs the DBD config readable only by root
sed -i "s|^After=.*|After=network.target munge.service mariadb.service|" \
  /etc/systemd/system/slurmdbd.service
systemctl daemon-reload
echo "    systemd reloaded"

# ---------------------------------------------------------------
# 7. Provide the binary names the rest of the scripts expect
# ---------------------------------------------------------------
hr "verifying installed binaries"
for b in slurmctld slurmd slurmdbd sacctmgr sinfo sbatch srun scontrol; do
  if [[ -x "${PREFIX}/sbin/$b" || -x "${PREFIX}/bin/$b" ]]; then
    echo "    ok: $b"
  else
    echo "    !! MISSING: $b"
  fi
done
"${PREFIX}/sbin/slurmctld" -V 2>&1 | head -1 | sed 's/^/    version: /'

echo
echo "==> slurm-source.sh DONE (Slurm ${SLURM_VER} at ${PREFIX})"
echo "    NOTE: systemd units must point at ${PREFIX}/sbin (see 03/04)."
